spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pr_dev
    username: .....
    password: ...
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
