spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb
      database:
  datasource:
    username:
    password:
    url: jdbc
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          release_mode: after_transaction
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
